import 'dart:convert';
import 'dart:typed_data';

import 'dart:ui';

import 'package:umbra_flutter/umbra_flutter.dart';

/// {@template giphy}
/// A Dart Shader class for the `giphy` shader.
/// {@endtemplate}
class Giphy extends UmbraShader {
  Giphy._() : super(_cachedProgram!);

  /// {@macro giphy}
  static Future<Giphy> compile() async {
    try {
      // Caching the program on the first compile call.
      _cachedProgram ??= await FragmentProgram.compile(
        spirv: Uint8List.fromList(base64Decode(_spirv)).buffer,
      );

      return Giphy._();
    } on Exception catch (err, stackTrace) {
      throw UmbraException(err, stackTrace);
    }
  }

  static FragmentProgram? _cachedProgram;

  Shader shader({
    required Size resolution,
    required double uTime,
  }) {
    return program.shader(
      floatUniforms: Float32List.fromList([
        uTime,
        resolution.width,
        resolution.height,
      ]),
      samplerUniforms: [],
    );
  }
}

const _spirv =
    'AwIjBwAAAQAKAA0AOwAAAAAAAAARAAIAAQAAAAsABgABAAAAR0xTTC5zdGQuNDUwAAAAAA4AAwAAAAAAAQAAAA8ABwAEAAAABAAAAG1haW4AAAAAKgAAADIAAAAQAAMABAAAAAgAAAADAAMAAQAAAEABAAAEAAoAR0xfR09PR0xFX2NwcF9zdHlsZV9saW5lX2RpcmVjdGl2ZQAABAAIAEdMX0dPT0dMRV9pbmNsdWRlX2RpcmVjdGl2ZQAFAAQABAAAAG1haW4AAAAABQAHAA0AAABmcmFnbWVudCh2ZjI7dmYyOwAAAAUAAwALAAAAdXYAAAUABQAMAAAAZnJhZ0Nvb3JkAAAABQADABAAAAB5AAAABQAFABQAAABmaW5hbENvbG9yMgAFAAMAKAAAAHV2AAAFAAYAKgAAAGdsX0ZyYWdDb29yZAAAAAAFAAUALgAAAHJlc29sdXRpb24AAAUABAAyAAAAX0NPTE9SXwAFAAQAMwAAAHBhcmFtAAAABQAEADUAAABwYXJhbQAAAAUABAA6AAAAdV90aW1lAABHAAMADQAAAAAAAABHAAMACwAAAAAAAABHAAMADAAAAAAAAABHAAMAEAAAAAAAAABHAAMAFAAAAAAAAABHAAMAFQAAAAAAAABHAAMAIAAAAAAAAABHAAMAIQAAAAAAAABHAAMAIgAAAAAAAABHAAMAIwAAAAAAAABHAAMAJAAAAAAAAABHAAMAJQAAAAAAAABHAAMAKAAAAAAAAABHAAQAKgAAAAsAAAAPAAAARwADAC4AAAAAAAAARwAEAC4AAAAeAAAAAQAAAEcAAwAvAAAAAAAAAEcAAwAyAAAAAAAAAEcABAAyAAAAHgAAAAAAAABHAAMAMwAAAAAAAABHAAMANAAAAAAAAABHAAMANQAAAAAAAABHAAMAOAAAAAAAAABHAAMAOgAAAAAAAABHAAQAOgAAAB4AAAAAAAAAEwACAAIAAAAhAAMAAwAAAAIAAAAWAAMABgAAACAAAAAXAAQABwAAAAYAAAACAAAAIAAEAAgAAAAHAAAABwAAABcABAAJAAAABgAAAAQAAAAhAAUACgAAAAkAAAAIAAAACAAAACAABAAPAAAABwAAAAYAAAArAAQABgAAABEAAAAAAIA/FwAEABIAAAAGAAAAAwAAACAABAATAAAABwAAABIAAAAUAAIAFgAAACsABAAGAAAAGAAAAG+BBD8rAAQABgAAABkAAADtnpw+LAAGABIAAAAaAAAAGAAAABkAAAAZAAAAKwAEAAYAAAAbAAAAAAAAACwABgASAAAAHAAAABsAAAAbAAAAGwAAABcABAAdAAAAFgAAAAMAAAAgAAQAKQAAAAEAAAAJAAAAOwAEACkAAAAqAAAAAQAAACAABAAtAAAAAAAAAAcAAAA7AAQALQAAAC4AAAAAAAAAIAAEADEAAAADAAAACQAAADsABAAxAAAAMgAAAAMAAAAgAAQAOQAAAAAAAAAGAAAAOwAEADkAAAA6AAAAAAAAADYABQACAAAABAAAAAAAAAADAAAA+AACAAUAAAA7AAQACAAAACgAAAAHAAAAOwAEAAgAAAAzAAAABwAAADsABAAIAAAANQAAAAcAAAA9AAQACQAAACsAAAAqAAAATwAHAAcAAAAsAAAAKwAAACsAAAAAAAAAAQAAAD0ABAAHAAAALwAAAC4AAACIAAUABwAAADAAAAAsAAAALwAAAD4AAwAoAAAAMAAAAD0ABAAHAAAANAAAACgAAAA+AAMAMwAAADQAAAA9AAQACQAAADYAAAAqAAAATwAHAAcAAAA3AAAANgAAADYAAAAAAAAAAQAAAD4AAwA1AAAANwAAADkABgAJAAAAOAAAAA0AAAAzAAAANQAAAD4AAwAyAAAAOAAAAP0AAQA4AAEANgAFAAkAAAANAAAAAAAAAAoAAAA3AAMACAAAAAsAAAA3AAMACAAAAAwAAAD4AAIADgAAADsABAAPAAAAEAAAAAcAAAA7AAQAEwAAABQAAAAHAAAAPgADABAAAAARAAAAPQAEAAYAAAAVAAAAEAAAALQABQAWAAAAFwAAABUAAAARAAAAUAAGAB0AAAAeAAAAFwAAABcAAAAXAAAAqQAGABIAAAAfAAAAHgAAABoAAAAcAAAAPgADABQAAAAfAAAAPQAEABIAAAAgAAAAFAAAAE8ACAASAAAAIQAAACAAAAAgAAAAAAAAAAEAAAAAAAAAUQAFAAYAAAAiAAAAIQAAAAAAAABRAAUABgAAACMAAAAhAAAAAQAAAFEABQAGAAAAJAAAACEAAAACAAAAUAAHAAkAAAAlAAAAIgAAACMAAAAkAAAAEQAAAP4AAgAlAAAAOAABAA==';
